### ISSUE TITLE
Comments on specific slides

### ISSUE THREAD

**Issue by alexenge** [KirstenStark/colab_r_github#2]
Beim Durchsehen der Folien ist mir aufgefallen:

- Ich würde gern am Anfang ein paar einleitende Worte sagen, bevor wir über die Tools sprechen, und habe dazu eine neue Folie 2 erstellt. Das macht eventuell deine Folie 6 ("0. Collaborating with yourself and others") etwas redundant. Wäre es für dich okay, wenn wir die weglassen? (Auch wenn der Talk von Adina großartig ist!)
- Für renv und Docker habe ich jeweils eine Titel-Folie erstellt, für die ich H1 (# ...) anstelle von H2 (## ...) für den Folientitel verwendet habe (das macht den Hintergrund blau). Magst du das übernehmen?
- Ich würde den konzeptuellen Titel der Tools (z.B. "Working in different contexts") nur auf der Titelfolie verwenden und dann auf den inhaltlichen Folien nur noch z.B. "RStudio Projects – How?". Ansonsten sind die Zuhörenden zu lange mit dem Lesen des Titels beschäftigt.
- Vielleicht können wir uns den Verweis auf das here-Package sparen? Das braucht man, wenn ich das richtig verstehe, nur, wenn man nicht mit Projects arbeitet (und hat denselben Effekt, dass man relative Pfade vom Projektordner aus verwenden kann).

Ansonsten sieht das alles klasse aus.

**Comment by KirstenStark** [comment]
So, ich bin gerade nochmal alle Slides durchgegangen und hätte noch folgende Vorschläge =) 

- [ ] Slide 2: Vielleicht bei Collaborating "code" auch kursiv? Ansonsten sieht es so aus, als wäre Definition von collaborating = history
- [ ] Slide 3: Heißt es nicht download TO your directory? Bin mir unsicher...
- [ ] Slide 47: Allows you to revert to the previous state when a PACKAGE update has broken your analysis?  Das Problem eines R updates löst renv ja noch nicht und grundsätzlich könnte ältere Package-Versionen auf einer neueren R-Version ja auch nicht mehr laufen
- [ ] Slide 48: Ich glaube, da fehlt das Wort "updating"n (Installing or updating a package)
- [ ] Slide 54: Hier fehlt ein Komma "Prevents differences between operating systems, R versions, region, and language settings etc."
- [ ] Slide 56: Detailed instructions
- [ ] Slide 67: Irgendwie finde ich das Abschlussbild wirkt ganz schön auf Drogen =D Finde ich nicht schlimm, aber leicht irritierend. Was hältst du alternativ davon: https://github.com/allisonhorst/stats-illustrations/blob/master/rstats-artwork/r_first_then.png

Ansonsten finde ich, die Präsentation sieht schon super aus!

**Comment by KirstenStark** [comment]
Ich hatte ursprünglich noch überlegt, bezüglich GitHub noch eine Folie mit einer Abbildung zur History/zum Vergleich von Diffs zu erstellen und eine zum Linken zu osf. Weil ich dann das Gefühl hatte, dass wir schon relativ viele Folien zu osf haben und das im Zweifelsfall recht selbsterklärend ist, habe ich die Folien dann doch erstmal weggelassen. Was denkst du?

**Comment by alexenge** [comment]
Finde ich gut. Ich denke die OSF-Integration ist selbsterklärend und es ist wichtiger, die neuen Tools gut zu vorstellen.

Und vielen Dank für die Anmerkungen oben!
